### ISSUE TITLE
csvkit-0.9.0 (and perhaps earlier) breaks csvsed's imports

### ISSUE THREAD

**Issue by metagriffin** [metagriffin/csvsed#1]
the following error occurs when using csvsed-0.2.3 with csvkit-0.9.0:

```
Traceback (most recent call last):
  File "/usr/local/bin/csvsed", line 9, in <module>
    load_entry_point('csvsed==0.2.3', 'console_scripts', 'csvsed')()
  File "/usr/lib/python2.7/dist-packages/pkg_resources.py", line 351, in load_entry_point
    return get_distribution(dist).load_entry_point(group, name)
  File "/usr/lib/python2.7/dist-packages/pkg_resources.py", line 2363, in load_entry_point
    return ep.load()
  File "/usr/lib/python2.7/dist-packages/pkg_resources.py", line 2088, in load
    entry = __import__(self.module_name, globals(),globals(), ['__name__'])
  File "/usr/local/lib/python2.7/dist-packages/csvsed/cli.py", line 17, in <module>
    from csvkit.cli import CSVKitUtility, CSVFileType, parse_column_identifiers
ImportError: cannot import name CSVFileType
```

**Comment by runeimp** [comment]
Is it possible (in PyPi) to update your tool to specify using an older version of `csvkit` as a workaround to fix this? Would a special directory with `virtualenv` to lock down `csvkit` < 0.9.0 and Python 2.7 a way to make this work? Are there any plans to upgrade to Python 3 and `csvkit-1.0.3`?
