### ISSUE TITLE
Import error on sed

### ISSUE THREAD

**Issue by CMCDragonkai** [metagriffin/csvsed#2]
```
Traceback (most recent call last):
  File "/home/cmcdragonkai/Projects/inverter-analysis/pip_packages/bin/csvsed", line 7, in <module>
    from csvsed.cli import main
  File "/home/cmcdragonkai/Projects/inverter-analysis/pip_packages/lib/python3.5/site-packages/csvsed/__init__.py", line 22, in <module>
    from sed import *
ImportError: No module named 'sed'
```

**Comment by runeimp** [comment]
Is there a chance with will ever get looked at? Is this project dead now? A note from the author would be much appreciated. 👼

**Comment by runeimp** [comment]
@CMCDragonkai This error appears to revolve around using this code with Python 3. If you pip install `csvsed` with Python 2 this error goes away. `csvsed` is still horribly broken but this particular error does go away.
